### PR TITLE
feat: added new section and updated CSS with fonts, responsiveness,

### LINKED ISSUE #18: [FEATURE] Adding new section and updating CSS with fonts, responsiveness, and enhancing Hover effect
• Want to add a new section for My favorite resources

• Updating the font-family

• Improving the hover effects with smooth background color transition and more 

• Enhancing responsiveness with new media queries for better layout on larger screens

• Adjusting font sizes and spacing for better readability

• Want to add box-shadow for enhanced visual depth

@michaella23 Can you please assign this issues to me ?

Thank You!

### PR DESCRIPTION
**Pull request by alienx5499**
and hover effects

- Added a new section for Prabal's favorite resources
- Updated font-family to include Georgia and Times New Roman
- Improved hover effects with smooth background color transition and border-radius
- Enhanced responsiveness with new media queries for better layout on larger screens
- Adjusted font sizes and spacing for better readability
- Added box-shadow for enhanced visual depth

I’m excited to hear your feedback and hope these updates enhance the user experience! 😊 Everything should now be visually appealing on all devices, so please take a look and share your thoughts! 🌟

Additionally, could you please add the “hacktoberfest-accepted” label to this PR and merge it when you have a moment? I would greatly appreciate it! 🙏

### CODE REVIEW

**Comment by alienx5499** [comment]
@michaella23 I’m excited to hear your feedback and hope these updates enhance the user experience! 😊 Everything should now be visually appealing on all devices, so please take a look and share your thoughts! 🌟
Additionally, could you please add the “hacktoberfest-accepted” label to this PR and merge it when you have a moment? I would greatly appreciate it! 🙏

**Review by michaella23 — CHANGES_REQUESTED** [review]
Hey @alienx5499, thanks for your checking out our project and submitting your pull request. It seems that you may not have read our CONTRIBUTING guidelines fully. It is better for our workflow if you can request to be assigned to an existing issue or a new issue that you would create (for example, all of the UI changes you made in the CSS file). If you would like to continue to contribute to this project, please confirm that you have read those guidelines.  
You made quite a lot of changes! I think most of them will work for this project, and it doesn't dramatically change the layout or adversely impact other code that has been written. I would like to keep the `text-underline` for all the links however, as this is a best practice for accessibility and is the expected display (for many people) to understand that the text they are looking at can be interacted with. 
I'll wait for those changes and your response, and I will approve your PR (and add the tag).

**Comment by alienx5499** [comment]
Hi @michaella23,

Thank you for reviewing my pull request and for the feedback! I appreciate the guidance on following the project’s CONTRIBUTING guidelines.

I’ve raised an issue corresponding to the changes I made in the pull request, as per your suggestion. Additionally, I have retained the underline for all links to ensure accessibility, as you recommended.

I’ve also taken the opportunity to optimize the CSS code, reducing complexity while keeping the functionality intact. Please let me know if there are any other adjustments you’d like me to make.

Looking forward to your approval!

Best regards,
@alienx5499

**Review by michaella23 — APPROVED** [review]
Thank you for the work you've done here Prabal. I really appreciate your professionalism and willingness to accept feedback. Merging your PR! Happy Hacktoberfest! 🎃

**Pull request merged**
